# Generated by Django 4.1.4 on 2023-06-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_service3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='service1',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service10',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service11',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service12',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service13',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service14',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service15',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service16',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service17',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service18',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service19',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service2',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service20',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service21',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service3',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service4',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service5',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service6',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service7',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service8',
        ),
        migrations.RemoveField(
            model_name='user',
            name='service9',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='incall_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='outcall_price',
            field=models.IntegerField(),
        ),
    ]
