# Generated by Django 4.1.4 on 2023-06-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_service1_remove_user_service10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(default='medium', max_length=20),
        ),
    ]
