# Generated by Django 4.1.4 on 2023-06-02 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='regular',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vip',
            field=models.BooleanField(default=False),
        ),
    ]
